"""
Django settings for party_management project.

Generated by 'django-admin startproject' using Django 5.2.6.
...
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@2w$&pr_dv^1h-efp=@in5w7+hckqql(6v=0e6#6on9gesmjn)'

# FIX 1: Use environment variable for DEBUG. True for local, False for Render.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = []
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Security and Host Settings
CSRF_TRUSTED_ORIGINS = [f'https://{RENDER_EXTERNAL_HOSTNAME}'] if RENDER_EXTERNAL_HOSTNAME else []

# Application definition

INSTALLED_APPS = [
    # Custom Apps
    'members',
    
    # Third-party Apps
    'crispy_forms',
    'crispy_bootstrap5',
    'whitenoise.runserver_nostatic', # Recommended for static file serving in development
    
    # Django Built-in Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise is correctly placed here for serving static files
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'party_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'party_management.wsgi.application'


# Database Configuration (Defaults to PostgreSQL locally)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'party_db',
        'USER': 'party_user',
        'PASSWORD': 'Wondej@2139',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# PRODUCTION/RENDER DATABASE CONFIGURATION (Overrides local settings)
DB_FROM_ENV = dj_database_url.config(conn_max_age=600)
DATABASES['default'].update(DB_FROM_ENV)


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# --- Static files (CSS, JavaScript, Images) Configuration ---

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# FIX 2: Only one STATIC_ROOT definition is needed. Use Path for consistency.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# FIX 3: Configure WhiteNoise to serve and compress static files.
# Requires: pip install whitenoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Custom/Additional Settings ---
MEDIA_URL = '/media/'

# FIX 4: Simplified MEDIA_ROOT logic using Path, and ensuring we default to local dev.
if 'RENDER' in os.environ:
    MEDIA_ROOT = '/var/data/media'
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# Authentication Settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'login_redirect'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@yourparty.com'

# Crispy Forms Settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
