# Generated by Django 4.2.24 on 2025-09-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='ሙሉ ስም')),
                ('gender', models.CharField(choices=[('Male', 'ወንድ'), ('Female', 'ሴት')], max_length=10, verbose_name='ጾታ')),
                ('date_of_birth', models.DateField(verbose_name='የትውልድ ቀን')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='member_photos/', verbose_name='ፎቶግራፍ')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='ስልክ ቁጥር')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ኢሜይል')),
                ('address_region', models.CharField(max_length=100, verbose_name='ክልል')),
                ('address_zone', models.CharField(max_length=100, verbose_name='ዞን')),
                ('address_woreda', models.CharField(max_length=100, verbose_name='ወረዳ')),
                ('address_kebele', models.CharField(max_length=100, verbose_name='ቀበሌ')),
                ('membership_id', models.CharField(blank=True, max_length=100, unique=True, verbose_name='የአባልነት መለያ ቁጥር')),
                ('membership_level', models.CharField(choices=[('Full', 'ሙሉ አባል'), ('Supporter', 'ደጋፊ')], max_length=50, verbose_name='የአባልነት ደረጃ')),
                ('party_role', models.CharField(blank=True, max_length=100, null=True, verbose_name='በፓርቲ ውስጥ ያለ ኃላፊነት')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='የተቀላቀለበት ቀን')),
                ('education_level', models.CharField(blank=True, max_length=100, null=True, verbose_name='የትምህርት ደረጃ')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='የስራ መስክ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='የአባልነት ሁኔታ (Active)')),
            ],
        ),
    ]
