# Generated by Django 4.2.24 on 2025-10-01 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0002_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_at', models.DateTimeField(auto_now_add=True, verbose_name='የተገኘበት ሰዓት')),
            ],
            options={
                'verbose_name_plural': 'Attendances',
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='የስብሰባው ርዕስ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='አጭር መግለጫ')),
                ('meeting_date', models.DateTimeField(verbose_name='የስብሰባው ቀን እና ሰዓት')),
                ('location', models.CharField(max_length=255, verbose_name='የስብሰባው ቦታ')),
                ('attendees', models.ManyToManyField(related_name='attended_meetings', through='members.Attendance', to='members.member', verbose_name='ተሰብሳቢዎች')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ፈጣሪ')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.meeting', verbose_name='ስብሰባ'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='አባል'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('member', 'meeting')},
        ),
    ]
